version: "3.8"
services:
    serversideup-web:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["php", "artisan", "migrate", "--force"]
        environment:
            - PHP_FPM_POOL_NAME=serversideup_web
            - PHP_OPCACHE_ENABLE=1
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:jxn1Jq7xu8txQMW1y0vWvJphSS8iy3oE7lclMPBqzoM=
            - APP_DEBUG=true
            - APP_TIMEZONE=UTC
            - APP_URL=http://localhost
            - APP_LOCALE=en
            - APP_MAINTENANCE_DRIVER=file
            - APP_MAINTENANCE_STORE=database
            - BCRYPT_ROUNDS=12
            - LOG_CHANNEL=stack
            - LOG_STACK=single
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_USERNAME=serversideup
            - DB_PASSWORD=serversideup
            - DB_DATABASE=serversideup
            - DB_PORT=3306
            - SESSION_DRIVER=database
            - SESSION_LIFETIME=120
            - SESSION_ENCRYPT=false
            - SESSION_PATH=/
            - SESSION_DOMAIN=null
            - BROADCAST_CONNECTION=log
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=redis
            - CACHE_STORE=database
            - CACHE_PREFIX=
            - MEMCACHED_HOST=127.0.0.1
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - MAIL_MAILER=log
            - MAIL_HOST=127.0.0.1
            - MAIL_PORT=2525
            - MAIL_USERNAME="Serversideup"
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
            - VITE_APP_NAME="${APP_NAME}"
        expose:
            - 8080

    serversideup-horizon:
        build:
            context: .
            dockerfile: Dockerfile-fpm
        environment:
            - PHP_FPM_POOL_NAME=serversideup_horizon
            - PHP_OPCACHE_ENABLE=1
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:jxn1Jq7xu8txQMW1y0vWvJphSS8iy3oE7lclMPBqzoM=
            - APP_DEBUG=true
            - APP_TIMEZONE=UTC
            - APP_URL=http://localhost
            - APP_LOCALE=en
            - APP_MAINTENANCE_DRIVER=file
            - APP_MAINTENANCE_STORE=database
            - BCRYPT_ROUNDS=12
            - LOG_CHANNEL=stack
            - LOG_STACK=single
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_DATABASE=serversideup
            - DB_USERNAME=serversideup
            - DB_PASSWORD=serversideup
            - DB_PORT=3306
            - SESSION_DRIVER=database
            - SESSION_LIFETIME=120
            - SESSION_ENCRYPT=false
            - SESSION_PATH=/
            - SESSION_DOMAIN=null
            - BROADCAST_CONNECTION=log
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=redis
            - CACHE_STORE=database
            - CACHE_PREFIX=
            - MEMCACHED_HOST=127.0.0.1
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - MAIL_MAILER=log
            - MAIL_HOST=127.0.0.1
            - MAIL_PORT=2525
            - MAIL_USERNAME="Serversideup"
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
            - VITE_APP_NAME="${APP_NAME}"

    redis:
        image: redis
        ports:
            - 6379:6379

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: serversideup
            MYSQL_USER: serversideup
            MYSQL_PASSWORD: serversideup
        ports:
            - 3306:3306
